enum ActionTypes {
  FETCH_OUTLET_IDENTIFIER = "FETCH_OUTLET_IDENTIFIER",
  FETCH_OUTLET_IDENTIFIER_SUCCESS = "FETCH_OUTLET_IDENTIFIER_SUCCESS",
  FETCH_OUTLET_IDENTIFIER_FAILED = "FETCH_OUTLET_IDENTIFIER_FAILED",
  RESET_STATE = "RESET_STATE",
}

export default ActionTypes;
